### ISSUE TITLE
support: UDM 1.9.2 has no data in USG nor USW dashboards (InfluxDB)

### ISSUE THREAD

**Issue by g40matt** [unpoller/unpoller#324]
First off - thank you!  What a great collection of tools.
One glitch I can't resolve is that 5 out of 6 dashboards are working, except the USG dashboard.  I have a UDM pro device acting as my security gateway.  Any tips on how to trouble shoot why no data is coming through?  FYI I'm on v6.1.70 of the controller and 1.9.2 of the UDM firmware.

**Comment by davidnewhall** [comment]
Can you share a screenshot so I know what's missing and which dashboard (influx/prometheus) you're using?

**Comment by g40matt** [comment]
Thanks!  Grafana 7.4.5, Influx 1.8.4, no prometheus, Unfi-poller 2.0.1-787.   Poller is running on a Raspberry Pi 4B, not in docker.  Controller is running on the UDM Pro.  The poller DOES NOT show the UDM stats or the UDM switch info on the USW dashboard. 

![image](https://user-images.githubusercontent.com/41497155/111934341-96d26e00-8a97-11eb-9612-e52ea918eedd.png)

**Comment by davidnewhall** [comment]
Probably turn on debug and see if the logs print any info about the UDM...

**Comment by g40matt** [comment]
![image](https://user-images.githubusercontent.com/41497155/111934592-19f3c400-8a98-11eb-862c-d879955611eb.png)

Looks like it is picking up a UDM

**Comment by davidnewhall** [comment]
Very strange.  Has this ever worked? Did upgrading to 1.9.2 break it? Another user opened an issue about 1.9.0, but I believe he got everything working. https://github.com/unifi-poller/unifi-poller/issues/315 - seems at least 1.9.0 is OK. I haven't had any other reports. 

Do you have a USW? I forget if the counter (you posted a screenshot of) includes UDM in the USW tally. If you do, does the USW show up no the USW dashboard OK?

**Comment by g40matt** [comment]
I just installed unifi-poller yesterday, so i dont know if 1.9.2 broke it.  

I do have a USW and it is showing up correctly in the USW dashboard.

**Comment by davidnewhall** [comment]
If you run `unifi-poller -j devices` it will print out all your device info. If you send that to me I can do a deeper dive. It does contain mac addresses, IPs, serial numbers and device names. My email is david at sleepers dot pro.

I'm just not sure what's going on here. UDM has been working great for many folks. That output format may have changed in 1.9.2, or your setup may not be emitting metrics for the device. Seeing that output will let me figure that out.

**Comment by davidnewhall** [comment]
I made a new release tonight. Maybe give that a shot. It doesn't have anything specific to this issue, but perhaps it has some magic.

**Comment by davidnewhall** [comment]
Something else comes to mind: make sure the device (UDM) has a unique name and not a MAC address. I don't know if this can cause issues, but it may.

**Comment by g40matt** [comment]
So... I rebooted my UDM and now the data is flowing to the USG dashboard and the UDM switch shows on the USG dashboard.  Odd!  FWIW, the UDM devices were showing up when i ran unifi-poller -j devices before the reboot.  I'll keep trouble shooting to see if there's something repeatable here.

Also, I noticed on the UAP dashboard that the "guests" count shows zero, while the "users" count is the sum of both "users" and "guests".  Currently I have 40 clients on the APs, 22 are users and 18 are guests (per Unifi's dashboard) but the UAP dashboard shows 40 users and 0 guests.

**Comment by g40matt** [comment]
Also, I did upgrade to your newest version.  That by itself didn't get it to work.  Before upgrading, unifi-poller showed 1 USG/UDM but no data in the dashboard.  After the upgrade, unifi-poller showed 0 USG/UDM (and still no data in the dashboard).  After the reboot, unifi-poller picked up the UDM and the dashboards started to populate.

**Comment by davidnewhall** [comment]
This is all great information. A stuck UDM had been reported before and it's good to know a reboot gets it going. 

I appreciate the dashboard feedback. I'm working on updates to them now, so I'll make sure the user counts are corrected. 

Thank you for the updates!

**Comment by absoluteg** [comment]
Just mentioning that there are beta releases of unifi controller for both UDM-Pro (like all the devices) but we also have that issue with the new UXG-Pro (Next-Gen Gateway Pro).  Much of this thread sounds similar to the other issue that you have been working on.  @davidnewhall - I'm still having an issue (even after installing all new unifi-poller instance today) with this device showing up under USG/UDM.  I'm still seeing a 0.  I would imagine that this would show USG/UDM/UXG as it's the replacement to the USG.  I don't want to redirect this thread by any means!  Simply saying that UDM and UXG still seem to have some reporting issues for itself.  Thank you for all the great work!!

**Comment by davidnewhall** [comment]
Hey @absoluteg! The original issue here was resolved by rebooting the UDM. I think with the UXG I just have some more work to do to make it work. I was too optimistic and skipped some things, like output. (whoops) I'm leaving _this_ task open to remind to:
- **Fix the user / guest counters on the UAP dashboard.**

**Comment by diegobaccino** [comment]
Hi folks, also running Controller Version 6.1.70 on UDMP version 1.9.2. Are you seeing issues on LAN counters on the USG page. I wondering if this is an open issue in the new version or if there is something else going on. I rebooted the USG a few times, still no LAN data. 
![image](https://user-images.githubusercontent.com/34780852/112712728-56576380-8e8e-11eb-95a8-05e1aed6d581.png)

Counters coming as 0 in influxDb. 
![image](https://user-images.githubusercontent.com/34780852/112712783-b948fa80-8e8e-11eb-9a84-8804f55c8beb.png)
![image](https://user-images.githubusercontent.com/34780852/112712801-cfef5180-8e8e-11eb-8b81-8ddd8886a79c.png)

Any ideas? Any help would be appreciated. Love the UnifiPoller. ❤
Cheers.

**Comment by davidnewhall** [comment]
Run `unifi-poller -j d` and see if the data is in the API response.

**Comment by diegobaccino** [comment]
Thanks @davidnewhall . I see the port_table under the USG in the data but it's not coming thru in the Influx. Are the below the fields you would expect. 

` "port_table": [
        {
          "port_idx": 1,
          "media": "GE",
          "port_poe": false,
          "speed_caps": 1048623,
          "op_mode": "switch",
          "portconf_id": "5e77d786d1dcea02e1b404cf",
          "autoneg": true,
          "enable": true,
          "flowctrl_rx": false,
          "flowctrl_tx": false,
          "full_duplex": true,
          "is_uplink": false,
          "mac": "e0:63:da:88:57:1f",
          "name": "LAN",
          "num_port": 1,
          "rx_broadcast": 7889,
          "rx_bytes": 37989328,
          "rx_dropped": 201,
          "rx_errors": 0,
          "rx_multicast": 7334,
          "rx_packets": 231375,
          "rx_rate": 51600,
          "rx_rate-max": 396032,
          "speed": 1000,
          "tx_broadcast": 1441,
          "tx_bytes": 468799892,
          "tx_dropped": 0,
          "tx_errors": 0,
          "tx_multicast": 1815,
          "tx_packets": 486276,
          "tx_rate": 97800,
          "tx_rate-max": 32908976,
          "type": "ethernet",
          "up": true,
          "ifname": "eth0",
          "ip": "192.168.0.1",
          "netmask": "255.255.255.0",
          "tx_bytes-r": 19496,
          "rx_bytes-r": 3569,
          "bytes-r": 23065,
          "port_security_mac_address": [],
          "network_name": "lan",
          "masked": false,
          "aggregated_by": false
        },`
        
        
![image](https://user-images.githubusercontent.com/34780852/112714848-c15a6780-8e99-11eb-8760-cc0bd0a2c23f.png)

But for some odd reason, the data is not making it in the tables. 
![image](https://user-images.githubusercontent.com/34780852/112714945-3fb70980-8e9a-11eb-8b2c-11b082c8d5e5.png)


Interestingly enough, the this data is being captured in the USW_ports table (UDMP as a switch) but not in the UDM table. 
![image](https://user-images.githubusercontent.com/34780852/112715011-c8ce4080-8e9a-11eb-93ac-b399fea3eec4.png)

**Comment by davidnewhall** [comment]
I believe you're graphing `rx_bytes` and `tx_bytes`. I don't believe I used any of the `-r` variables. Are those numbers changing? Your screenshot shows data on the graphs...

**Comment by diegobaccino** [comment]
Sorry- correct. Looking at `rx_bytes` and `tx_bytes`. The numbers are changing in every API call I make.. But just not landing on Influx. 
The screenshot shows data on the graph on the `usw_ports` measure. But the dashboard template for USG looks at the `usg` measure. Those stopped working sometime around 3/14 for me. I think that's when my controller updated to the latest version. 

![image](https://user-images.githubusercontent.com/34780852/112726802-84fc2b00-8edc-11eb-940d-8c115bac7616.png)

**Comment by davidnewhall** [comment]
This is where the data comes in from the API: https://github.com/unifi-poller/unifi/blob/master/usg.go#L230-L233
This is where the data is written to InfluxDB: https://github.com/unifi-poller/influxunifi/blob/master/usg.go#L70-L75
You can see it's pretty much a 1:1 mapping. This is what it looks like in my `unifi-poller -j d` output:
```
      "stat": {
        "gw": {
          "site_id": "574e86994566ffb914a2683c",
          "o": "gw",
          "oid": "74:43:a2:1b:25:39",
          "gw": "74:43:a2:1b:25:39",
          "time": 1616760600000,
          "datetime": "2021-03-26T12:10:00Z",
          "duration": 161603000,
          "lan-rx_packets": 150814690,
          "lan-rx_bytes": 171934118243,
          "lan-tx_packets": 125454796,
          "lan-tx_bytes": 71944620631,
          "wan-rx_packets": 125362274,
          "wan-rx_bytes": 75149839373,
          "wan-tx_packets": 149582953,
          "wan-tx_bytes": 171278694546,
          "wan-rx_dropped": 1431,
          "lan-rx_dropped": 39
        }
      },
```

Same question: Are your numbers changing? Did they move the data somewhere else? That `stat` json I pasted above should be on the same level as the USG device, kinda like you see below. If they moved it (which they've done before), it may throw it off and cause zeros. You're welcome to send me your entire json payload and I can check this: david at sleepers dot pro.
```
    {
      "_id": "5d5ba3168f038502155a1020",
      "ip": "67.xx1.x5.x20",
      "mac": "74:43:a2:1b:25:39",
      "model": "UGW4",
      "type": "ugw",
      "version": "4.4.52.5363507",
      ...
      "stat": { ..stuff.. },
```

I run the command like this to make it pretty:
```
unifi-poller -j d | grep wan | jq . > unifi-devices.json
```

**Comment by diegobaccino** [comment]
The interface RX and TX numbers are changing under the `port_table` but it looks like UBNT is no longer aggregating those numbers under the GW (gateway) `stat` array 🙁  I'll send you a redacted JSON copy of the output in case you want to look at it. Thanks 😊

```
 "stat": {
        "gw": {
          "site_id": "5e77d783d1dcea02e1b404bb",
          "o": "gw",
          "oid": "e0:63:da:88:57:1f",
          "gw": "e0:63:da:88:57:1f",
          "time": 1616827200000,
          "datetime": "2021-03-27T06:40:00Z",
          "duration": 151491000
        },
```

**Comment by ikkerus** [comment]
I'm running the first CloudKey with 6.1.71 and wanna try and help by bringing in some more JSON information.
My unifi-poller is running on docker. But since there's no "bash/sh" available: Is  there any way to post information from executing the "unifi-poller -j d" command?

By the way: My setup is showing the WAN throughput:

<img width="800" alt="Bildschirmfoto 2021-03-29 um 05 57 56" src="https://user-images.githubusercontent.com/67939/112785224-ce22bb00-9053-11eb-8c24-ad0bc12df9dc.png">

**What version of Grafana?**
7.4.5
**What version of InfluxDB?**
1.8.4
What version of unifi-poller?
Docker:latest
**Where does poller run?**
unRAID OS, on Docker environment
**Where does your controller run?**
UC-CK (CloudKey 1st Generation)
**How many devices is poller collecting?**
Devices: Not more than 10, Clients 60-100

**Comment by davidnewhall** [comment]
You can do this on unRAID:
```docker run --rm -it golift/unifi-poller -j d```

**Comment by ikkerus** [comment]
Thanks for the help, with that it was quite easy to achieve, but for debugging purposes I would also suggest to run in on baremetal. Well, maybe I'll migrate to a Raspberry Pi 4 once you did the next major change.

Running it with "prep" didn't grep the right part, but I've sent you the complete JSON file.

unRAID: 
`docker run --rm -it -e 'UP_UNIFI_CONTROLLER_0_USER'='unifipoller' -e 'UP_UNIFI_CONTROLLER_0_PASS'='$password' -e 'UP_UNIFI_CONTROLLER_0_URL'='$ipaddress' golift/unifi-poller -j d | grep wan | jq > /mnt/user/isos/unifipoller.json`

**Comment by davidnewhall** [comment]
The `grep` is just to get rid of the stuff that's not json. The entire payload will contain all devices. A fancier `jq` command can select only specific ones, but sending me all the json is preferred, then I can check _everything_. Thank you for sending that!

re, bad format: use 3 ticks instead of 1, I edited your comment to fix it. Check it out!

**Comment by platinummonkey** [comment]
closing in favor of #333 ^
